### PR TITLE
Minor changes in dataLoader.py

### PR DESCRIPTION
**Pull request by starcanmd**
I have corrected some grammar mistakes.

### CODE REVIEW

**Comment by birm** [comment]
Hello, thank you for the PR!
Interestingly, I don't seem to have write access to this repository now. All the same, this is more or less an archival repository. I'm curious how you're using the caMicroscope/QUIP stack.

In any case, thanks again for contributing. I'll direct this to someone who still has write access here.

**Comment by starcanmd** [comment]
Hello Ryan,

I am planning to apply for GSoC -I'm a masters student- this year. While I
was looking over the old projects I came across the caMicroscope repository
and it caught my attention. I'm a doctor as well and very interested in the
machine learning applications in healthcare setting. I'm planning to apply
for PhD in Machine Learning (Biomedical Engineering Department) in
GeorgiaTech. Actually, I have been following the works of Gari Clifford for
a while and it would be incredible to have the opportunity to work with
him. Do you happen to have any suggestions about this? It would be
invaluable.

Also, thank you for directing my request. Have a good day.

Hande

**Comment by birm** [comment]
Hello Hande,

While we're in the same department as Dr. Clifford, the caMicroscope team doesn't work with him directly. I did, however, reach out to one of his postdocs, who recommended looking at the projects here (https://github.com/cliffordlab) but not before becoming at least reasonably familiar with each project's purpose, and identifying if there are associated papers.

However, if your interest is with caMicroscope (digital pathology), let us know how you'd like to contribute. The tool we're using in place of this (imageLoader.py) repository is SlideLoader (https://github.com/camicroscope/SlideLoader).

**Comment by starcanmd** [comment]
Hello Ryan,

First of all, thank you for taking an extra step to help. I will do what
the postdoc has suggested. Would you mind, if it will not cause you any
trouble, sharing the name of the postdoc -in case I have a specific
questions about contributing to their projects through GitHub? Also, I
would be happy to work on caMicroscope. I'm currently working as a research
engineer in a company that is producing solutions for pathologist, using
deep learning. So, it is safe to say that I'm very interested in digital
pathology. This week I will look into caMicroscope thoroughly and let you
know what I can help with.

Thank you for your help again. Have a good day.

Best regards,
Serim Hande Tarcan

**Comment by birm** [comment]
Closed as we're archiving this repository. The current similar tool is https://github.com/camicroscope/SlideLoader/

**Pull request closed without merging**
